### ISSUE TITLE
Idk what this is

### ISSUE THREAD

**Issue by AnomalyJx** [LUXTACO/Brwler#2]
Traceback (most recent call last):
  File "C:\Users\Ogooluwa.taiwo\Documents\Brwler-main\bin\farmer.py", line 194, in <module>
    match = match_custom(title)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\Documents\Brwler-main\bin\farmer.py", line 68, in match_custom
    image = locateOnScreen('./med/start.png', confidence=0.5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 378, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 356, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ogooluwa.taiwo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 215, in _locateAll_opencv
    raise ValueError('needle dimension(s) exceed the haystack image or region dimensions')
ValueError: needle dimension(s) exceed the haystack image or region dimensions

**Comment by LUXTACO** [comment]
Try updating the screenshots
